# Generated by Django 5.0.6 on 2024-06-18 14:16

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', api.models.ORJSONDecodedField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SampleSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.FloatField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sample')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.target')),
            ],
        ),
        migrations.CreateModel(
            name='UmapPlotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coor', models.FloatField()),
                ('y_coor', models.FloatField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sample')),
            ],
        ),
    ]
