# Generated by Django 5.0.6 on 2024-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='plate_barcode',
            field=models.CharField(db_index=True, default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='well_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
